server:
    port: 443
    ssl:
        key-store: classpath:cert/foundfun.fun.jks
        #这个是在生成证书的时候设置的密码
        key-store-password: 214751764880967
#fzk:
#  port: 8091
spring:
#返回的前缀   目录对应src/main/webapp下
    mvc:
        view:
            prefix: classpath:static/view/
            suffix: .html
    thymeleaf:
#        prefix: classpath:/static/view/
#        suffix: .html
        cache: false
    datasource:
       type: com.alibaba.druid.pool.DruidDataSource
#       druid: #监控统计拦截的filters
#      filters: stat
       #基本属性
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://47.106.153.232:3306/dd_main0?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
       username: fangln
       password: fangln1991!
       #配置初始化大小/最小/最大
       initial-size: 5
       min-idle: 1
       max-active: 20
       #获取连接等待超时时间
       max-wait: 60000
       #间隔多久进行一次检测，检测需要关闭的空闲连接
       time-between-eviction-runs-millis: 60000
       #一个连接在池中最小生存的时间
       min-evictable-idle-time-millis: 300000
       validation-query: SELECT 1 FROM DUAL
       test-while-idle: true
       test-on-borrow: false
       test-on-return: false
       #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
       pool-prepared-statements: false
       max-pool-prepared-statement-per-connection-size: 20
mybatis:
  mapper-locations: classpath:com.fangln.dd.dao/*.xml
  type-aliases-package: com.fangln.dd.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql